spring.application.name=orbital

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.cloud.aws.region.static=eu-north-1
spring.h2.console.enabled=true
spring.cloud.aws.credentials.access-key=
spring.cloud.aws.credentials.secret-key=

aws.dynamodb.endpoint=http://localhost:8000
server.address=0.0.0.0
server.port=3000
